"""add_milestone_decisions

Revision ID: 19bc99b2b9ee
Revises: 76d2b3f4f184
Create Date: 2026-04-29 16:26:20.700144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19bc99b2b9ee'
down_revision: Union[str, Sequence[str], None] = '76d2b3f4f184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestone_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'approved', 'rejected', 'superseded', name='milestonedecisionstatus'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestone_decisions_id'), 'milestone_decisions', ['id'], unique=False)
    op.create_index(op.f('ix_milestone_decisions_milestone_id'), 'milestone_decisions', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_milestone_decisions_task_id'), 'milestone_decisions', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_milestone_decisions_task_id'), table_name='milestone_decisions')
    op.drop_index(op.f('ix_milestone_decisions_milestone_id'), table_name='milestone_decisions')
    op.drop_index(op.f('ix_milestone_decisions_id'), table_name='milestone_decisions')
    op.drop_table('milestone_decisions')
    # ### end Alembic commands ###
