"""add_sprint_model

Revision ID: 6ff5de88b5d6
Revises: f836fa8d42c6
Create Date: 2026-04-26 13:44:47.087874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff5de88b5d6'
down_revision: Union[str, Sequence[str], None] = 'f836fa8d42c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

sprintstatus = sa.Enum('planned', 'active', 'closed', name='sprintstatus')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    sprintstatus.create(bind, checkfirst=True)
    op.create_table('sprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sprintstatus, nullable=True),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sprints_id'), 'sprints', ['id'], unique=False)
    op.add_column('tasks', sa.Column('sprint_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_tasks_sprint_id', 'tasks', 'sprints', ['sprint_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tasks_sprint_id', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'sprint_id')
    op.drop_index(op.f('ix_sprints_id'), table_name='sprints')
    op.drop_table('sprints')
    sprintstatus.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
